[package]
name = "poly-stc-contracts"
version = "0.0.1"
authors = ["9191stc (9191stc@gmail.com)"]

[addresses]
NamedAddr = "0x18351d311d32201149a4df2a9fc2db8a"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin.git", subdir = "vm/stdlib", rev = "3e895169a8f8dd883277050bb90645c52a370cee" }