[package]
name = "Poly-STC-Bridge"
version = "1.0.1"

[addresses]
StarcoinFramework = "0x1"
Bridge = "0xe52552637c5897a2d499fbf08216f73e"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "0404a536621cd3899053685e65f525c4d2513f70" }