[package]
name = "Bridge-STC-Utils"
version = "2.0.1"

[addresses]
StarcoinFramework = "0x1"
Bridge = "0xe52552637c5897a2d499fbf08216f73e"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "2ee2378d0d6eaa4ebc1ac6d3e33c4aee11bc2fe4" }