[package]
name = "Poly-Crosschain"
version = "2.0.1"

[addresses]
StarcoinFramework = "0x1"
Bridge = "0xe52552637c5897a2d499fbf08216f73e"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "01c84198819310620f2417413c3c800df8292ae5" }
STC-SMT = { local = "../stc-smt" }
STC-Utils = { local = "../stc-utils" }