[package]
name = "Bridge-STC-SMT"
version = "2.0.1"

[addresses]
StarcoinFramework = "0x1"
Bridge = "0xdfe8ca002624bcaecb4188da78d42043"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "aaedc734971551c9df26a0bcc11b7c925264c8a4" }
Bridge-STC-Utils = { local = "../stc-utils" }